name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
        
      - name: Install dependencies
        run: npm install
      - name: Build Tauri App
        run: npm run build
        
      - name: "Upload build artifact: Windows Installer (msi)"
        uses: actions/upload-artifact@v4
        with:
          name: "MCCManager 0.3.5 Windows"
          path: |
            D:\a\MCCManager\MCCManager\src-tauri\target\release\bundle\msi\mccmanager_0.3.5_x64_en-US.msi
            
      - name: "Upload build artifact: Other Installer (exe)"
        uses: actions/upload-artifact@v4
        with:
          name: "MCCManager 0.3.5 Other"
          path: |
            D:\a\MCCManager\MCCManager\src-tauri\target\release\bundle\nsis\mccmanager_0.3.5_x64-setup.exe
      - name: "Upload build artifact: Debug exe file"
        uses: actions/upload-artifact@v4
        with:
          name: Debug exe file
          path: |
            D:\a\MCCManager\MCCManager\src-tauri\target\release\mccmanager.exe
